/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Sections/': RouteRecordInfo<'/Sections/', '/Sections', Record<never, never>, Record<never, never>>,
    '/Settings/': RouteRecordInfo<'/Settings/', '/Settings', Record<never, never>, Record<never, never>>,
    '/Settings/Content/': RouteRecordInfo<'/Settings/Content/', '/Settings/Content', Record<never, never>, Record<never, never>>,
    '/Settings/Menus/': RouteRecordInfo<'/Settings/Menus/', '/Settings/Menus', Record<never, never>, Record<never, never>>,
    '/Settings/Menus/Item/': RouteRecordInfo<'/Settings/Menus/Item/', '/Settings/Menus/Item', Record<never, never>, Record<never, never>>,
    '/Settings/TitleBar/': RouteRecordInfo<'/Settings/TitleBar/', '/Settings/TitleBar', Record<never, never>, Record<never, never>>,
  }
}
