/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Google Gemini copy - version 1.0.0
 *
 * Gemini 是谷歌公司发布的人工智能大模型，能够在从数据中心到移动设备等不同平台上运行。
 *
 * OpenAPI version: 3.0.1
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.post_v1_models_gemini_pro_generatecontent': ['POST', '/v1/models/gemini-pro:generateContent'],
  'general.post_v1beta_models_gemini_pro_generatecontent': ['POST', '/v1beta/models/gemini-pro:generateContent'],
  'general.post_v1_models_gemini_pro_streamgeneratecontent': ['POST', '/v1/models/gemini-pro:streamGenerateContent'],
  'general.post_v1_models_gemini_pro_vision_generatecontent': ['POST', '/v1/models/gemini-pro-vision:GenerateContent']
};
