/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Layout: typeof import('./../components/Layout/index.vue')['default']
    LayoutMenus: typeof import('./../components/Layout/Menus/index.vue')['default']
    LayoutSiderBar: typeof import('./../components/Layout/SiderBar/index.vue')['default']
    LayoutSiderBarMenus: typeof import('./../components/Layout/SiderBar/Menus/index.vue')['default']
    LayoutTitleBar: typeof import('./../components/Layout/TitleBar/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sections: typeof import('./../pages/Sections/index.vue')['default']
    Settings: typeof import('./../pages/Settings/index.vue')['default']
    SettingsContent: typeof import('./../pages/Settings/Content/index.vue')['default']
    SettingsMenus: typeof import('./../pages/Settings/Menus/index.vue')['default']
    UIButton: typeof import('./../components/UI/Button/index.vue')['default']
    UIRichEditor: typeof import('./../components/UI/RichEditor/index.vue')['default']
  }
}
