/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Document: typeof import('./../pages/document/index.vue')['default']
    Layout: typeof import('./../components/Layout/index.vue')['default']
    LayoutMenus: typeof import('./../components/Layout/Menus/index.vue')['default']
    LayoutSiderBar: typeof import('./../components/Layout/SiderBar/index.vue')['default']
    LayoutTitleBar: typeof import('./../components/Layout/TitleBar/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NModalProvider: typeof import('naive-ui')['NModalProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sections: typeof import('./../pages/Sections/index.vue')['default']
    Settings: typeof import('./../pages/Settings/index.vue')['default']
    SettingsContent: typeof import('./../pages/Settings/Content/index.vue')['default']
    SettingsContentAiSettingForm: typeof import('./../pages/Settings/Content/aiSettingForm.vue')['default']
    SettingsFunction: typeof import('./../pages/Settings/Function/index.vue')['default']
    SettingsMenus: typeof import('./../pages/Settings/Menus/index.vue')['default']
    SettingsMenusItem: typeof import('./../pages/Settings/Menus/Item/index.vue')['default']
    SettingsTitleBar: typeof import('./../pages/Settings/TitleBar/index.vue')['default']
    UIButton: typeof import('./../components/UI/Button/index.vue')['default']
    UIForm: typeof import('./../components/UI/Form/index.vue')['default']
    UIInput: typeof import('./../components/UI/Input/index.vue')['default']
    UIRichEditor: typeof import('./../components/UI/RichEditor/index.vue')['default']
    UISelect: typeof import('./../components/UI/Select/index.vue')['default']
  }
}
