/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * OpenAI（ChatGPT） - version 1.0.0
 *
 * Open AI（ChatGPT）几乎可以应用于任何涉及理解或生成自然语言或代码的任务。我们提供一系列具有不同功率级别的模型，适用于不同的任务，并且能够微调您自己的自定义模型。这些模型可用于从内容生成到语义搜索和分类的所有领域。


 *
 * OpenAPI version: 3.0.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.post_v1_audio_speech': ['POST', '/v1/audio/speech'],
  'general.post_v1_audio_transcriptions': ['POST', '/v1/audio/transcriptions'],
  'general.post_v1_audio_translations': ['POST', '/v1/audio/translations'],
  'general.post_v1_chat_completions': ['POST', '/v1/chat/completions'],
  'general.post_v1_completions': ['POST', '/v1/completions'],
  'general.post_v1_embeddings': ['POST', '/v1/embeddings'],
  'general.post_v1_fine_tuning_jobs': ['POST', '/v1/fine_tuning/jobs'],
  'general.get_v1_fine_tuning_jobs': ['GET', '/v1/fine_tuning/jobs'],
  'general.get_v1_fine_tuning_jobs_fine_tuning_job_id': ['GET', '/v1/fine_tuning/jobs/{fine_tuning_job_id}'],
  'general.post_v1_fine_tuning_jobs_fine_tuning_job_id_cancel': [
    'POST',
    '/v1/fine_tuning/jobs/{fine_tuning_job_id}/cancel'
  ],
  'general.get_v1_fine_tuning_jobs_fine_tuning_job_id_events': [
    'GET',
    '/v1/fine_tuning/jobs/{fine_tuning_job_id}/events'
  ],
  'general.post_v1_images_generations': ['POST', '/v1/images/generations'],
  'general.post_v1_images_edits': ['POST', '/v1/images/edits'],
  'general.post_v1_images_variations': ['POST', '/v1/images/variations'],
  'general.get_v1_models': ['GET', '/v1/models'],
  'general.get_v1_models_modelid': ['GET', '/v1/models/{modelid}'],
  'general.get_v1_models_model': ['GET', '/v1/models/{model}'],
  'general.post_v1_files': ['POST', '/v1/files'],
  'general.get_v1_files': ['GET', '/v1/files'],
  'general.delete_v1_files_file_id': ['DELETE', '/v1/files/{file_id}'],
  'general.get_v1_files_file_id': ['GET', '/v1/files/{file_id}'],
  'general.get_v1_files_file_id_content': ['GET', '/v1/files/{file_id}/content'],
  'general.post_v1_moderations': ['POST', '/v1/moderations'],
  'general.post_v1_assistants': ['POST', '/v1/assistants'],
  'general.get_v1_assistants': ['GET', '/v1/assistants'],
  'general.get_v1_assistants_assistant_id': ['GET', '/v1/assistants/{assistant_id}'],
  'general.post_v1_assistants_assistant_id': ['POST', '/v1/assistants/{assistant_id }'],
  'general.delete_v1_assistants_assistant_id': ['DELETE', '/v1/assistants/{assistant_id }'],
  'general.post_v1_assistants_assistant_id_files': ['POST', '/v1/assistants/{assistant_id}/files'],
  'general.get_v1_assistants_assistant_id_files': ['GET', '/v1/assistants/{assistant_id}/files'],
  'general.get_v1_assistants_assistant_id_files_file_id': ['GET', '/v1/assistants/{assistant_id}/files/{file_id }'],
  'general.delete_v1_assistants_assistant_id_files_file_id': [
    'DELETE',
    '/v1/assistants/{assistant_id}/files/{file_id }'
  ],
  'general.post_v1_threads': ['POST', '/v1/threads'],
  'general.post_v1_threads_thread_id': ['POST', '/v1/threads/{thread_id }'],
  'general.delete_v1_threads_thread_id': ['DELETE', '/v1/threads/{thread_id }'],
  'general.post_v1_threads_thread_id_messages': ['POST', '/v1/threads/{thread_id}/messages'],
  'general.get_v1_threads_thread_id_messages': ['GET', '/v1/threads/{thread_id}/messages'],
  'general.get_v1_threads_thread_id_messages_message_id': ['GET', '/v1/threads/{thread_id}/messages/{message_id }'],
  'general.post_v1_threads_thread_id_messages_message_id': ['POST', '/v1/threads/{thread_id}/messages/{message_id }'],
  'general.get_v1_threads_thread_id_messages_message_id_files_file_id': [
    'GET',
    '/v1 /threads/{thread_id}/messages/{message_id}/files/{file_id}'
  ],
  'general.get_v1_threads_thread_id_messages_message_id_files__': [
    'GET',
    '/v1/threads/{thread_id}/messages/{message_id}/files _'
  ],
  'general.post_v1_threads_thread_id_runs': ['POST', '/v1/threads/{thread_id}/runs'],
  'general.get_v1_threads_thread_id_runs': ['GET', '/v1/threads/{thread_id}/runs'],
  'general.get_v1_threads_thread_id_runs_run_id': ['GET', '/v1/threads/{thread_id}/runs/{run_id }'],
  'general.post_v1_threads_thread_id_runs_run_id_submit_tool_outputs': [
    'POST',
    '/v1/threads/{thread_id}/runs/{run_id}/submit_tool_outputs'
  ],
  'general.post_v1_threads_thread_id_runs_run_id_cancel': ['POST', '/v1/threads/{thread_id}/runs/{run_id}/cancel'],
  'general.post_v1_threads_runs': ['POST', '/v1/threads/runs'],
  'general.get_v1_threads_thread_id_runs_run_id_steps_step_id': [
    'GET',
    '/v1 /threads/{thread_id}/runs/{run_id}/steps/{step_id}'
  ],
  'general.get_v1_threads_thread_id_runs_run_id_steps': ['GET', '/v1/threads/{thread_id}/runs/{run_id}/steps']
};
